//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LeaveDBModel", "FK_EmployeeLeaves_LeaveTypes", "LeaveTypes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LeaveSystemEx.LeaveTypes), "EmployeeLeaves", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LeaveSystemEx.EmployeeLeaves))]

// Original file name:
// Generation date: 3/1/2011 7:45:25 PM
namespace LeaveSystemEx
{
    
    /// <summary>
    /// There are no comments for LeaveDBEntities in the schema.
    /// </summary>
    public partial class LeaveDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new LeaveDBEntities object using the connection string found in the 'LeaveDBEntities' section of the application configuration file.
        /// </summary>
        public LeaveDBEntities() : 
                base("name=LeaveDBEntities", "LeaveDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LeaveDBEntities object.
        /// </summary>
        public LeaveDBEntities(string connectionString) : 
                base(connectionString, "LeaveDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LeaveDBEntities object.
        /// </summary>
        public LeaveDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LeaveDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for EmployeeLeaves in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EmployeeLeaves> EmployeeLeaves
        {
            get
            {
                if ((this._EmployeeLeaves == null))
                {
                    this._EmployeeLeaves = base.CreateQuery<EmployeeLeaves>("[EmployeeLeaves]");
                }
                return this._EmployeeLeaves;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EmployeeLeaves> _EmployeeLeaves;
        /// <summary>
        /// There are no comments for LeaveTypes in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LeaveTypes> LeaveTypes
        {
            get
            {
                if ((this._LeaveTypes == null))
                {
                    this._LeaveTypes = base.CreateQuery<LeaveTypes>("[LeaveTypes]");
                }
                return this._LeaveTypes;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LeaveTypes> _LeaveTypes;
        /// <summary>
        /// There are no comments for EmployeeLeaves in the schema.
        /// </summary>
        public void AddToEmployeeLeaves(EmployeeLeaves employeeLeaves)
        {
            base.AddObject("EmployeeLeaves", employeeLeaves);
        }
        /// <summary>
        /// There are no comments for LeaveTypes in the schema.
        /// </summary>
        public void AddToLeaveTypes(LeaveTypes leaveTypes)
        {
            base.AddObject("LeaveTypes", leaveTypes);
        }
    }
    /// <summary>
    /// There are no comments for LeaveDBModel.EmployeeLeaves in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeleaveId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LeaveDBModel", Name="EmployeeLeaves")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EmployeeLeaves : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EmployeeLeaves object.
        /// </summary>
        /// <param name="employeeleaveId">Initial value of EmployeeleaveId.</param>
        public static EmployeeLeaves CreateEmployeeLeaves(int employeeleaveId)
        {
            EmployeeLeaves employeeLeaves = new EmployeeLeaves();
            employeeLeaves.EmployeeleaveId = employeeleaveId;
            return employeeLeaves;
        }
        /// <summary>
        /// There are no comments for Property EmployeeleaveId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeleaveId
        {
            get
            {
                return this._EmployeeleaveId;
            }
            set
            {
                this.OnEmployeeleaveIdChanging(value);
                this.ReportPropertyChanging("EmployeeleaveId");
                this._EmployeeleaveId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeleaveId");
                this.OnEmployeeleaveIdChanged();
            }
        }
        private int _EmployeeleaveId;
        partial void OnEmployeeleaveIdChanging(int value);
        partial void OnEmployeeleaveIdChanged();
        /// <summary>
        /// There are no comments for Property EmployeeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                this.OnEmployeeIdChanging(value);
                this.ReportPropertyChanging("EmployeeId");
                this._EmployeeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EmployeeId");
                this.OnEmployeeIdChanged();
            }
        }
        private string _EmployeeId;
        partial void OnEmployeeIdChanging(string value);
        partial void OnEmployeeIdChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this.ReportPropertyChanging("StartDate");
                this._StartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartDate");
                this.OnStartDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this.ReportPropertyChanging("EndDate");
                this._EndDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDate");
                this.OnEndDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for LeaveTypes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LeaveDBModel", "FK_EmployeeLeaves_LeaveTypes", "LeaveTypes")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public LeaveTypes LeaveTypes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LeaveTypes>("LeaveDBModel.FK_EmployeeLeaves_LeaveTypes", "LeaveTypes").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LeaveTypes>("LeaveDBModel.FK_EmployeeLeaves_LeaveTypes", "LeaveTypes").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for LeaveTypes in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<LeaveTypes> LeaveTypesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LeaveTypes>("LeaveDBModel.FK_EmployeeLeaves_LeaveTypes", "LeaveTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<LeaveTypes>("LeaveDBModel.FK_EmployeeLeaves_LeaveTypes", "LeaveTypes", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LeaveDBModel.LeaveTypes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LeaveTypeId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LeaveDBModel", Name="LeaveTypes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LeaveTypes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LeaveTypes object.
        /// </summary>
        /// <param name="leaveTypeId">Initial value of LeaveTypeId.</param>
        public static LeaveTypes CreateLeaveTypes(int leaveTypeId)
        {
            LeaveTypes leaveTypes = new LeaveTypes();
            leaveTypes.LeaveTypeId = leaveTypeId;
            return leaveTypes;
        }
        /// <summary>
        /// There are no comments for Property LeaveTypeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveTypeId
        {
            get
            {
                return this._LeaveTypeId;
            }
            set
            {
                this.OnLeaveTypeIdChanging(value);
                this.ReportPropertyChanging("LeaveTypeId");
                this._LeaveTypeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LeaveTypeId");
                this.OnLeaveTypeIdChanged();
            }
        }
        private int _LeaveTypeId;
        partial void OnLeaveTypeIdChanging(int value);
        partial void OnLeaveTypeIdChanged();
        /// <summary>
        /// There are no comments for Property LeaveType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LeaveType
        {
            get
            {
                return this._LeaveType;
            }
            set
            {
                this.OnLeaveTypeChanging(value);
                this.ReportPropertyChanging("LeaveType");
                this._LeaveType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LeaveType");
                this.OnLeaveTypeChanged();
            }
        }
        private string _LeaveType;
        partial void OnLeaveTypeChanging(string value);
        partial void OnLeaveTypeChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for EmployeeLeaves in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LeaveDBModel", "FK_EmployeeLeaves_LeaveTypes", "EmployeeLeaves")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<EmployeeLeaves> EmployeeLeaves
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<EmployeeLeaves>("LeaveDBModel.FK_EmployeeLeaves_LeaveTypes", "EmployeeLeaves");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<EmployeeLeaves>("LeaveDBModel.FK_EmployeeLeaves_LeaveTypes", "EmployeeLeaves", value);
                }
            }
        }
    }
}
